FROM ubuntu:16.04

RUN apt update
RUN apt install -y info libncurses5 g++ make
RUN apt install -y vim

RUN apt-get install -y g++-multilib gdb coreutils python3-pexpect capnproto 

COPY --from=debug_tools /usr/local/gdb /usr/local/gdb
COPY --from=debug_tools /usr/local/rr  /usr/local/rr
COPY --from=debug_tools /usr/local/valgrind /usr/local/valgrind
