FROM ubuntu:16.04

RUN apt update
RUN apt install -y info libncurses5 g++ make python
RUN apt install -y vim

RUN apt-get install -y g++-multilib gdb coreutils python3-pexpect capnproto 

COPY --from=build_debuggers /usr/local/gdb /usr/local/gdb
COPY --from=build_debuggers /usr/local/rr  /usr/local/rr
COPY --from=build_debuggers /usr/local/valgrind /usr/local/valgrind
